id: A0F119373
title: Food Offering Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.072484
  last_modified_at: 2022-03-01 06:27:18.072495
