id: A0F119373
title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
  for the Female Practice of the Ḍākinī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.063074
  last_modified_at: 2022-03-01 06:27:18.063078
