id: A0F119373
title: Concise Tsok Feast
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.067414
  last_modified_at: 2022-03-01 06:27:18.067418
