id: A0F119373
title: Brief Prayer of the Feast Gathering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.065852
  last_modified_at: 2022-03-01 06:27:18.065855
