id: A0F119373
title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
  Heart Drop'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.080840
  last_modified_at: 2022-03-01 06:27:18.080842
