id: A0F119373
title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the Sixfold
  Satisfaction of the Maṇḍala of the Feast-Gathering'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.077946
  last_modified_at: 2022-03-01 06:27:18.077949
