id: A0F119373
title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the Tsok
  Feast Offering to Venerable and Exalted Vajrayoginī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.074109
  last_modified_at: 2022-03-01 06:27:18.074111
