id: A0F119373
title: A Concise Feast Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.061563
  last_modified_at: 2022-03-01 06:27:18.061571
