id: A0F119373
title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.075471
  last_modified_at: 2022-03-01 06:27:18.075474
