id: A0F119373
title: 'Ḍākinī’s Delight: A Song of the Feast'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.083576
  last_modified_at: 2022-03-01 06:27:18.083578
