id: A0F119373
title: Song of the Feast (Tsok Lu)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.079309
  last_modified_at: 2022-03-01 06:27:18.079311
