id: A0F119373
title: Short Tsok Offering to the Powerful Lady Kurukullā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.076392
  last_modified_at: 2022-03-01 06:27:18.076395
