id: A0F119373
title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the Vajra
  Seven-Line Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:18.071289
  last_modified_at: 2022-03-01 06:27:18.071296
